package tw.com.mds.fet.femtocellportal.core;

public enum UserLogType {

	SEARCH_USERPROFILES,
	CREATE_USER_AND_PROFILE,
	CREATE_PROFILE,
	CHANGE_PERMISSION_LIST,
	CHANGE_UEPERMISSIONMODE,
	CHANGE_PROFILE,
	SUSPEND_PROFILE,
	RESUME_PROFILE,
	DELETE_PROFILE,
	ADMINUSER_LOGIN,
	ADMINUSER_LOGOUT,
	FEMTOUSER_LOGIN,
	FEMTOUSER_LOGOUT,
	ADMINUSER_LOGINFAILED,
	FEMTOUSER_LOGIN_FAILED,
	CHANGE_LOCATIONDETECTMODE, 
	SYSTEM_MANAGEMENT 
	
}
