alter table Cell drop constraint FK1FFD82B7AB84E4;
alter table FemtoProfile drop constraint FK667ECB00C2E6B915;
alter table FemtoProfile drop constraint FK667ECB00554E4C76;
alter table FemtoProfileCell drop constraint FK24414882D9592F40;
alter table FemtoProfileCell drop constraint FK24414882F4679A93;
alter table Permission drop constraint FK57F7A1EF10CD3F2A;
alter table UserEquipment drop constraint FKE4D75DE3F0D55D69;
drop table AdminUser;
drop table Announcement;
drop table ApZone;
drop table Cell;
drop table FemtoProfile;
drop table FemtoProfileCell;
drop table FemtoUser;
drop table NE_STG_3G_HW_CELL;
drop table Permission;
drop table Rnc;
drop table UserEquipment;
drop table UserLog;
create table AdminUser (oid numeric(19,0) identity not null, account varchar(50) not null, createTime datetime not null, email varchar(100) null, password varchar(100) null, updateTime datetime not null, userId varchar(50) not null, userName varchar(50) null, primary key (oid), unique (userId));
create table Announcement (oid numeric(19,0) identity not null, content varchar(1000) null, createTime datetime not null, endTime datetime not null, startTime datetime not null, title varchar(100) null, updateTime datetime not null, userType int not null, primary key (oid));
create table ApZone (oid numeric(19,0) identity not null, createTime datetime not null, name varchar(128) not null, updateTime datetime not null, primary key (oid));
create table Cell (oid numeric(19,0) identity not null, cell_id varchar(20) not null, cell_name varchar(20) null, createTime datetime not null, dir int null, lacId varchar(20) not null, lat_idx int null, lon_idx int null, mcc varchar(50) null, mnc varchar(50) null, plmId varchar(20) not null, lat numeric(14,10) not null, lon numeric(14,10) not null, type int not null, updateTime datetime not null, ven varchar(50) null, rnc_oid numeric(19,0) null, primary key (oid), unique (rnc_oid, cell_id));
create table FemtoProfile (oid numeric(19,0) identity not null, address varchar(200) not null, apei varchar(21) not null, connectionMode int null, createTime datetime not null, imsi varchar(15) not null, locatingState int null, locationDetectMode int null, maxPermissionListSize int null, maxUserCount int not null, latitude numeric(14,10) not null, longitude numeric(14,10) not null, state int not null, staticIp varchar(25) null, uePermissionMode int not null, updateTime datetime not null, apZone_oid numeric(19,0) not null, user_oid numeric(19,0) not null, primary key (oid), unique (apei, imsi));
create table FemtoProfileCell (FemtoProfile_oid numeric(19,0) not null, cells_oid numeric(19,0) not null);
create table FemtoUser (oid numeric(19,0) identity not null, account varchar(50) null unique, cardId varchar(32) null, createTime datetime not null, mobile varchar(16) null unique, password varchar(50) null, phone varchar(16) null, updateTime datetime not null, userName varchar(50) null, zipCode varchar(10) null, primary key (oid));
create table NE_STG_3G_HW_CELL (oid numeric(19,0) identity not null, beamdirection varchar(5) null, cellid varchar(10) null, cellname varchar(10) null, hspdschcodenum varchar(5) null, hspdschmaxcodenum varchar(5) null, hspdschmincodenum varchar(5) null, hsscchcodenum varchar(5) null, lac varchar(5) null, latitude varchar(20) null, locell varchar(10) null, longitude varchar(20) null, maxhsdpausernum varchar(10) null, maxtxpower varchar(5) null, mcc varchar(5) null, mnc varchar(5) null, nodebname varchar(10) null, pcpichpower varchar(10) null, pschpower varchar(10) null, pscrambcode varchar(5) null, rac varchar(5) null, rnc_id varchar(10) null, rncname varchar(10) null, sac varchar(5) null, uarfcndownlink varchar(5) null, uarfcnuplink varchar(5) null, primary key (oid));
create table Permission (oid numeric(19,0) identity not null, createTime datetime not null, resourceId varchar(100) not null, adminUser_oid numeric(19,0) not null, primary key (oid), unique (adminUser_oid, resourceId));
create table Rnc (oid numeric(19,0) identity not null, createTime datetime not null, rncId varchar(10) not null, rncName varchar(50) null, updateTime datetime not null, primary key (oid), unique (rncId));
create table UserEquipment (oid numeric(19,0) identity not null, imsi varchar(15) not null, msisdn varchar(15) not null, profile_oid numeric(19,0) not null, primary key (oid));
create table UserLog (oid numeric(19,0) identity not null, content varchar(4000) null, createTime datetime not null, operatorId varchar(50) null, operatorName varchar(50) null, operatorSourceIp varchar(50) null, profileApei varchar(21) null, profileImsi varchar(15) null, type int not null, userMobile varchar(16) null, userName varchar(50) null, primary key (oid));
alter table Cell add constraint FK1FFD82B7AB84E4 foreign key (rnc_oid) references Rnc;
alter table FemtoProfile add constraint FK667ECB00C2E6B915 foreign key (user_oid) references FemtoUser;
alter table FemtoProfile add constraint FK667ECB00554E4C76 foreign key (apZone_oid) references ApZone;
alter table FemtoProfileCell add constraint FK24414882D9592F40 foreign key (FemtoProfile_oid) references FemtoProfile;
alter table FemtoProfileCell add constraint FK24414882F4679A93 foreign key (cells_oid) references Cell;
alter table Permission add constraint FK57F7A1EF10CD3F2A foreign key (adminUser_oid) references AdminUser;
alter table UserEquipment add constraint FKE4D75DE3F0D55D69 foreign key (profile_oid) references FemtoProfile;
